services:
  - type: web
    name: ml-cv-prediction
    runtime: python
    runtimeVersion: 3.11.10
    buildCommand: bash build.sh
    startCommand: cd backend && gunicorn -w 2 -b 0.0.0.0:$PORT main:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PYTHONUNBUFFERED
        value: 1
